### ISSUE TITLE
Crash before/during call-gtc_tsv, difficult to interpret the error message...

### ISSUE THREAD

**Issue by Jolleboll** [freeseek/mocha#26]
Error message:

`[2022-04-27 11:50:34,79] [info] BackgroundConfigAsyncJobExecutionActor [e38dbc61mocha.gtc_tsv:NA:1]: job id: 22366
[2022-04-27 11:50:34,79] [info] BackgroundConfigAsyncJobExecutionActor [e38dbc61mocha.gtc_tsv:NA:1]: Status change from - to Done
[2022-04-27 11:50:35,16] [info] WorkflowManagerActor: Workflow e38dbc61-b064-4141-9c6a-e5d54d6dd2f3 failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'if_condition' (reason 1 of 1): Evaluating (length(idx2gtc2vcf_files[idx]) > 1) failed: Bad Map access idx2gtc2vcf_files[idx]: This Map[Int, Array[String]] does not have a Int index value [5]
        at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$7(WorkflowExecutionActor.scala:563)
        at scala.collection.immutable.List.map(List.scala:293)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableNodes(WorkflowExecutionActor.scala:557)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:211)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:209)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
        at akka.actor.FSM.processEvent(FSM.scala:710)
        at akka.actor.FSM.processEvent$(FSM.scala:704)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:54)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:847)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:829)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:54)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:701)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:695)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$receive$1.applyOrElse(WorkflowExecutionActor.scala:507)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$Timers$$super$aroundReceive(WorkflowExecutionActor.scala:54)
        at akka.actor.Timers.aroundReceive(Timers.scala:51)
        at akka.actor.Timers.aroundReceive$(Timers.scala:40)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:54)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
        at akka.actor.ActorCell.invoke(ActorCell.scala:583)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by Jolleboll** [comment]
I think maybe it is related to whether there are batches in the batch table file that have no samples in the sample table file.
